apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectfour-deployment
spec:
  replicas: 12
  selector:
    matchLabels:
      app: connectfour
  template:
    metadata:
      labels:
        app: connectfour
    spec:
      containers:
        - name: connectfour-web
          image: wentzien/connectfour-client:1.0.2
          env:
            - name: API_URL
              value: https://api.connectfour.wntzn.com
          resources:
            requests:
              cpu: 100m
              memory: 254Mi
            limits:
              cpu: 200m
              memory: 512Mi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: connectfour-ip-service
spec:
  type: LoadBalancer
  selector:
    app: connectfour
  ports:
    - port: 80
      targetPort: 80
